Real-Dev-Squad/tiny-site-frontend

Doc/Product Requirements Document.md

Tiny Site is a user-friendly website that reduces the length of your URL(Uniform Resource Locator). The idea is to minimize the web page address into something that’s easier to remember and track. This web application will maintain connection between the new URL and the original URL, meaning that anyone who clicks on your new URL will be redirected to the original page.
**The objectives of the tiny site are as follows:**
- Create a user-friendly web application to generate short URLs for long and complex ones, facilitating easy sharing and improved memorability.
- Enable users to track and analyze URL statistics, including access frequency and timestamps of accesses.
- Provide customization options, such as adding aliases to URLs and configuring URL properties (e.g., alias length, …

DOC: add product requirements documents

---

.eslintignore
.eslintrc
.gitignore
.prettierignore
__tests__/hello.test.tsx
jest.config.js
jest.setup.js
package.json
src/app/hello.tsx
yarn.lock

TEST(SETUP): Add testing library

---

src/components/Button/index.tsx
src/components/ProfileIcon/ProfileIcon.tsx
src/pages/dashboard/index.tsx
src/pages/login/index.tsx
src/types/button.types.ts
src/types/profileIcon.types.ts
src/utils/constants.ts

- common imports for types in `src/types`
- common imports for constants in `src/utils/constants.ts`

Common imports for types/ interfaces/ utils/ constants/ services

---

.github/workflows/pre-commit-checks.yml

- #65 
Add checks for build in GitHub Workflow
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
N/A
N/A
N/A

Workflow: add checks for build

---

__tests__/utils/shortenUrl.test.ts
src/utils/shortenUrl.ts

-  #69 
This pull request fixes an issue with the response for short URLs, as it was not being passed correctly.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No

fix: change response attributes

---

package.json
yarn.lock

-   #56 
React query package added
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
N/A
N/A
N/A

react-query -1: add react query package

---

__tests__/components/Redirect/ErrorPage.test.tsx
__tests__/pages/[redirect].test.tsx
src/components/App/OutputSection.tsx
src/components/Redirect/ErrorPage.tsx
src/components/ShimmerEffect/RedirectShimmer.tsx
src/pages/[redirect]/index.tsx

-   #86
In this pull request, the redirect page has been enhanced with the addition of a shimmer effect for a more visually appealing user experience. An error message has also been incorporated, accompanied by a reload button to improve user interaction. The changes have been made to address issue #86.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] No
-   [ ] Yes
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------|---------|----------|---------|---------|-------------------
All files                     |   97.36 |     92.1 |   93.67 |   98.45 | …

Corrected Redirect Page with Shimmer Effect and Reload Button for Error Message

---

Doc/Technical Requirements Documents.md

-   #3 
- Technical Requirements Documents for Tiny Site
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
- N/A
- N/A
- N/A

DOC: TRD for Tiny Site

---

__tests__/components/CreateNew.test.tsx
__tests__/components/Navbar/UserProfileButton.test.tsx
__tests__/utils/formatDate.test.ts
src/components/CreateNew/index.tsx
src/components/Layout/index.tsx
src/components/Navbar/NavbarMenuItems.tsx
src/components/Navbar/UserProfileButton.tsx
src/components/Navbar/index.tsx
src/components/Redirect/LoaderTimer.tsx
src/pages/_app.js

- **Hamburger Menu Arrow Rotation:**
- Updated the CSS and animation script to ensure the hamburger menu arrow rotates smoothly when the menu is opened.
- **Hamburger Icon Design:**
- Replaced the odd five-line design of the hamburger icon with the arrow design for a more consistent and recognized look.
- **Plus Icon Visibility:**
- Implemented conditional checks to hide or disable the plus icon specifically in the "create new page" context, improving the overall user experience.
- **Countdown Animation:**
- Adjusted the styling of the countdown animation to create adequate spacing, preventing any visual annoyance by ensuring it no longer touches the surrounding text.
https://github.com/Real-Dev-Squad/tiny-site-frontend/assets/70854507/b57002ec-8d58-4e1d-b854-3ddf7183c4a2 …

fix: some bugs and some improvement in create new button

---

__tests__/pages/[redirect].test.tsx
src/pages/[redirect]/index.tsx

Update redirect count doun from 5-3
Provide a concise description of the changes made in this PR.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
_Indicate whether the changes include modifications to the …

Update redirect count doun from 5-3

---

src/pages/app/index.tsx

-   closes #92 
Currently when we create a tiny URL then API call will happen twice so in this PR this issue has been resolved
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No …

Fix unnecessary post call

---

__tests__/components/QRCodeModal.test.tsx
package.json
src/components/App/OutputSection.tsx
src/components/QRCodeModal/index.tsx
yarn.lock

-   #101
This Pull Request addresses issue #101: "Generate QR Code and Download for Shortened URL". The goal is to introduce a feature within the Issuu platform that enables users to generate a QR code for a shortened URL and provides the option to download the QR code.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
https://github.com/Real-Dev-Squad/tiny-site-frontend/assets/70854507/6b277c46-31cc-4db3-9642-da94c6b09ed8
| File                             | Lines (%) | Statements (%) | Branches (%) | Functions (%) |
| -------------------------------- | --------- | -------------- | ------------ | ------------- |
| …

FEATURE: Implement QR Code Generation and Download for Shortened URL

---

__mocks__/handlers/url.ts
src/pages/[redirect]/index.tsx
src/services/api.tsx

- https://github.com/Real-Dev-Squad/tiny-site-backend/pull/66
-   https://github.com/Real-Dev-Squad/tiny-site-backend/issues/67
Change the API endpoint for get URL list
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No …

change get all urls route and redirect api url

---

src/constants/url.ts

As the API name has been changed from tinyurl to redirect in the backend so In frontend it also should be changed 
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
_Indicate whether the changes include modifications …

Fix redirect api

---

src/components/QRCodeModal/index.tsx

-   Closes #106 
Fixed the issue where the short URL QR code was not working. Updated the QR code generation process to ensure proper redirection to the intended URL.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
- Manual testing of QR code scanning on multiple devices to ensure proper redirection.

fix: qr code for short url

---

__tests__/components/Dashhboard/UrlList.test.tsx
__tests__/components/Dashhboard/UrlListItem.test.tsx
src/components/Dashboard/UrlListItem.tsx
src/components/Loader/index.tsx
src/pages/_app.tsx
src/pages/app/index.tsx
src/services/api.tsx

- Add button to delete a shortened url
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No

add button to delete a shortened url on dashboard

---

src/components/Dashboard/UrlList.tsx
src/components/Dashboard/UrlListItem.tsx

Provide a concise description of the changes made in this PR.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
Attach any relevant screenshots, …

add remaining count on dashboard & fix css

---

src/components/Navbar/index.tsx

Add withd to logo image
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
Attach any relevant screenshots, such as test coverage reports, before and after images, or other visual aids.
Provide information on the test …

Add withd to logo image

---

package.json
yarn.lock

Reverts Real-Dev-Squad/tiny-site-frontend#117

Revert "Add sharp as dependency"

---

src/components/Navbar/index.tsx

Provide a concise description of the changes made in this PR.
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
Attach any relevant screenshots, …

[HOT FIX]fix image size

---

src/pages/_app.tsx
src/services/api.tsx

-  closes #129 
Fix multiple calls of user URLs APi
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
https://github.com/user-attachments/assets/74ca5400-56f9-4310-9c1c-da574abe55c4
Include any additional notes, …

Fix mutiple api calls for user urls api

---

__tests__/pages/[redirect].test.tsx
src/components/Navbar/DesktopMenu.tsx
src/pages/[redirect]/index.tsx
src/pages/dashboard/index.tsx

Fix the minor UI bugs
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
Attach any relevant screenshots, such as test coverage reports, before and …

 fix UI bugs

---

.env.development
.env.production
.env.staging
__tests__/components/App/OutputSection.test.tsx
__tests__/components/App/SortenUrlForm.test.tsx
src/components/App/OutputSection.tsx
src/components/App/ShortenUrlForm.tsx
src/components/Navbar/DesktopMenu.tsx
src/components/Navbar/index.tsx
src/pages/[redirect]/index.tsx
src/utils/validateUrl.ts

-   closes #143 
In this PR 
- Fix navbar alignment and logo redirection
- fix Url validation regex
- icons size in mobile
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
Provide information on the test coverage for the …

Fix UI adjustment 

---

__tests__/pages/dashboard.test.tsx
src/pages/dashboard/index.tsx

Date: 15-09-2024
Developer Name: vinit
**PR going to Sync**
- #147 
https://github.com/user-attachments/assets/0938eab7-f7db-410a-acfd-99121140dca6

Dev to Main Sync

---

src/components/Layout/index.tsx

-   closes #151 
Fix the image URL to load meta image
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
Attach any relevant screenshots, such as test coverage reports, before and after images, or other visual aids.
Provide …

fix og-image url

---

__tests__/components/Dashhboard/UrlListItem.test.tsx
src/components/Dashboard/UrlListItem.tsx
src/services/api.tsx

-   
Remove userId to pass in body for create and delete URL body
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
https://github.com/user-attachments/assets/b4db26ef-fc77-47ea-8d15-8521dbca9439
Provide information on the …

Fix create and delete url  api
